-- Written by Noel Heim, modified by John Czaplewski
-- fill collection_types  THIS COULD BE SHORTENED, I'VE MADE IT GENERAL SO THE DATABASE SCHEMA AND STANDARDS COULD BE USED ON OTHER PROJECTS
INSERT INTO neodb.collection_types (collection_type, modified_on) 
VALUES ('insects', now()),
  ('molluscs', now()),
  ('other invertebrates', now()),
  ('herps', now()),
  ('small mammals', now()),
  ('large mammals', now()),
  ('birds', now()),
  ('trees', now()),
  ('shrubs', now()),
  ('herbs', now()),
  ('marine and aquatic plants', now()),
  ('plankton', now()),
  ('meiofauna', now()),
  ('generic', now()),
  ('unknown', now());

-- fill geom_bases
INSERT INTO neodb.geom_bases (geom_basis, modified_on) 
VALUES ('gps WGS84', now()),
  ('gps GRS80', now()),
  ('Google Earth WGS84', now()),
  ('estimated from map', now()),
  ('address', now()),
  ('municipality', now()),
  ('county/parish', now()),
  ('state/province', now()),
  ('geographic feature', now());


--  fill collection_methods
-- fill institutions  THIS IS DUMMY DATA
INSERT INTO neodb.institutions (id, institution_name, institution_abbrev, country, geom_basis_id, the_geom, modified_on, url, is_repository) 
VALUES (1, 'University of Wisconsin-Madison', 'UW', 'USA', 3, ST_GeomFromText('POINT(-89.4061 43.0707)',4326), now(), 'http://www.wisc.edu/', DEFAULT),
  (2, 'Ohio Museum of Biological Diversity', 'MBD', 'USA', 3, ST_GeomFromText('POINT(-83.044 39.997)',4326), now(), 'http://mbd.osu.edu/', TRUE),
  (3, 'Ohio Joes Beetle Collection', 'Joe', 'USA', 3, ST_GeomFromText('POINT(-80.8144 41.2383)',4326), now(), NULL, TRUE),
  (4, 'Cleveland Museum of Natural History', 'CMNH', 'USA', 3, ST_GeomFromText('POINT(-81.612983 41.511381)',4326), now(), 'http://www.cmnh.org/', TRUE),
  (5, 'Cincinnati Museum Center', 'CMC', 'USA', 3, ST_GeomFromText('POINT(-84.5378 39.1100)',4326), now(), 'http://www.cincymuseum.org/', TRUE),
  (6, 'Carnegie Museum of Natural History', 'CarMNH', 'USA', 3, ST_GeomFromText('POINT(-79.9506 40.4436)',4326), now(), 'http://www.carnegiemnh.org/', TRUE),
  (7, 'Akron Janes Beetle Collection', 'Jane', 'USA', 3, ST_GeomFromText('POINT(-81.5115 41.0752)',4326), now(), NULL, TRUE);

-- fill people  THIS IS DUMMY DATA
INSERT INTO neodb.people (id, first_name, initials, last_name, title, institution_id, email, modified_on) 
VALUES (1, 'Test', 'TU', 'User', 'scientist', 1, 'tuser@test.org', now());

--  fill roles
INSERT INTO neodb.roles (id, role, authorizations, modified_on)
VALUES (1, 'administrator', 'full', now()),
  (2, 'authorizer', 'insert, update, select', now()),
  (3, 'enterer', 'insert, update, select', now()),
  (4, 'user', 'select', now()),
  (5, 'collector', 'none', now()),
  (6, 'taxon determiner', 'none', now()),
  (7, 'author', 'none', now()),
  (8, 'photographer', 'none', now());
  
--  fill people_roles  THIS IS DUMMY DATA
INSERT INTO neodb.people_roles (person_id, role_id, modified_on)
VALUES (1, 1, now());
  

--  fill collection_baits
INSERT INTO neodb.baits (bait, modified_on)
VALUES ('ethanol lure pack', now()),
  ('alpha pinene lure pack', now()),
  ('unknown', now());


--  fill collection_media
INSERT INTO neodb.collection_media (collection_medium, modified_on)
VALUES ('under bark', now()),
  ('under rocks', now()),
  ('in nest', now()),
  ('in burrow', now()),
  ('gravel', now()),
  ('sand', now()),
  ('silt', now()),
  ('mud', now()),
  ('soil', now()),
  ('unknown', now());



--  fill environments
INSERT INTO neodb.environments (environ, environ_type, environ_class, modified_on)
VALUES ('lacustrine','lacustrine','aquatic', now()),
  ('lacustrine, large','lacustrine','aquatic', now()),
  ('lacustrine, small','lacustrine','aquatic', now()),
  ('pond','lacustrine','aquatic', now()),
  ('mire/swamp','landscape','aquatic', now()),
  ('forest, hardwood','landscape','terrestrial', now()),
  ('tidal flat','coastal','marine', now()),
  ('beach','coastal','marine', now()),
  ('forest, upland hardwoods','landscape','terrestrial', now()),
  ('alpine','landscape','terrestrial', now()),
  ('alpine, above tree line','landscape','terrestrial', now()),
  ('alpine, below tree line','landscape','terrestrial', now()),
  ('tundra','landscape','terrestrial', now()),
  ('tundra, dry','landscape','terrestrial', now()),
  ('tundra, wet','landscape','terrestrial', now()),
  ('mangrove','landscape','paralic', now()),
  ('forest, pine','landscape','terrestrial', now());

--  fill taxa  THIS IS DUMMY DATA
INSERT INTO neodb.taxa (taxon_order, taxon_family, taxon_genus, taxon_species, pbdb_taxon_no, modified_on, common_name, taxon_rank, taxon_name)
VALUES ('Coleoptera', 'indet.', 'Laimocenos', 'striatogranulatus', 181984, now(), '', 'species', 'Laimocenos striatogranulatus'), 
  ('Coleoptera', 'Curculionidae', 'Pachnobium', 'dreuxi', 216394, now(), '', 'species', 'Pachnobium dreuxi'), 
  ('Coleoptera', 'indet.', 'Tomocoleites', 'longigastrulatus', 227681, now(), '', 'species', 'Tomocoleites longigastrulatus'), 
  ('Coleoptera', 'Lucanidae', 'Hexarthrius', 'parryi', NULL, now(), '', 'species', 'Hexarthrius parryi'), 
  ('Coleoptera', 'Scarabaeidae', 'Deltochilum', 'valgum', NULL, now(), '', 'species',  'Deltochilum valgum'), 
  ('Coleoptera', 'Scarabaeidae', 'Aegialia', 'rupta', 208954, now(), '', 'species', 'Aegialia rupta'), 
  ('Coleoptera', 'Scarabaeidae', 'Trox', '', 208880, now(), '', 'genus', 'Trox'),
  ('Coleoptera', 'Scarabaeidae', 'Popillia', 'japonica', NULL, now(), 'Japanese beetle', 'species', 'Popillia japonica'),
  ('Coleoptera', 'Nitidulidae', 'Aethina', 'tumida', NULL, now(), 'small hive beetle', 'species', 'Aethina tumida'),
  ('Coleoptera', 'Leiodidae', 'Platypsyllus', 'castoris', NULL, now(), 'beaver parasite beetle', 'species', 'Platypsyllus castoris'),
  ('Hymenoptera', 'Apidae', 'Apis', '', 70716, now(), 'honeybee', 'genus', 'Apis'),
  ('Rodentia', 'Castoridae', 'Castor', 'canadensis', 44957, now(), 'American beaver', 'species', 'Castor'),
  ('Fagales', 'Fagaceae', 'Quercus', '', 54594, now(), 'oak', 'genus', 'Quercus'),
  ('Fagales', 'Fagaceae', 'Quercus', 'vacciniifolia', NULL, now(), 'huckleberry oak', 'species', 'Quercus vacciniifolia'),
  ('Sapindales', 'Aceraceae', 'Acer', '', 54688, now(), 'maple', 'genus', 'Acer'),
  ('Asparagales', 'Orchidaceae', 'Arethusa', 'bulbosa', NULL, now(), 'Dragons mouth orchid', 'species', 'Arethusa bulbosa'),
  ('Primates', 'Hominidae', 'Homo', 'sapiens', 83088, now(), 'Humans', 'species', 'Homo sapiens'),
  ('Coleoptera', 'Scarabaeidae', 'Pelidnota', 'punctata', NULL, now(), 'grapevine beetle', 'species', 'Pelidnota punctata'),
  ('Vitales', 'Vitaceae', 'Vitis', 'riparia', NULL, now(), 'river bank grape', 'species', 'Vitis riparia'); 
INSERT INTO neodb.taxa (taxon_order, taxon_family, pbdb_taxon_no, modified_on, common_name, taxon_rank, taxon_name)
VALUES ('Coleoptera', 'Lucanidae', 69301, now(), 'stag beetle', 'family', 'Lucanidae'),
  ('Coleoptera', 'Coccinellidae', 69479, now(), 'ladybug or ladybird', 'family', 'Coccinellidae'),
  ('Coleoptera', 'Geotrupidae', 69306, now(), 'dor or earth-boring beetle', 'family', 'Geotrupidae');
INSERT INTO neodb.taxa (taxon_order, taxon_family, taxon_genus, taxon_species, pbdb_taxon_no, modified_on, common_name, taxon_author, taxon_rank, taxon_name)   
VALUES ('Carnivora', 'Felidae', 'Lynx', 'canadensis', 47819, now(), 'Canada lynx', 'Kerr 1792', 'species', 'Lynx canadensis');
INSERT INTO neodb.taxa (taxon_genus, taxon_species, common_name, modified_on, taxon_name)
VALUES  ('Abies','amabilis','Pacific silver fir', now(), 'Abies amabilis'),
  ('Abies','balsamea','balsam fir', now(), 'Abies balsamea'),
  ('Abies','bracteata','bristlecone fir', now(), 'Abies bracteata'),
  ('Abies','concolor','white fir', now(), 'Abies concolor'),
  ('Abies','fraseri','Fraser fir', now(), 'Abies fraseri'),
  ('Abies','grandis','grand fir', now(), 'Abies grandis'),
  ('Abies','lasiocarpa','subalpine fir', now(), 'Abies lasiocarpa'),
  ('Abies','magnifica','California red fir', now(), 'Abies magnifica'),
  ('Abies','procera','noble fir', now(), 'Abies procera'),
  ('Acacia','berlandieri','Berlandier acacia', now(), 'Acacia berlandieri'),
  ('Acacia','choriophylla','cinnecord', now(), 'Acacia choriophylla'),
  ('Acacia','farnesiana','sweet acacia', now(), 'Acacia farnesiana'),
  ('Acacia','greggii','catclaw acacia', now(), 'Acacia greggii'),
  ('Acacia','macracantha','long spine acacia', now(), 'Acacia macracantha'),
  ('Acacia','rigidula','blackbrush acacia', now(), 'Acacia rigidula'),
  ('Acacia','roemeriana','Roemer acacia', now(), 'Acacia roemeriana'),
  ('Acacia','tortuosa','twisted acacia', now(), 'Acacia tortuosa'),
  ('Acacia','wrightii','Wright acacia', now(), 'Acacia wrightii'),
  ('Acer','barbatum','Florida maple', now(), 'Acer barbatum'),
  ('Acer','circinatum','vine maple', now(), 'Acer circinatum'),
  ('Acer','glabrum','Rocky Mountain maple', now(), 'Acer glabrum'),
  ('Acer','grandidentatum','bigtooth maple', now(), 'Acer grandidentatum'),
  ('Acer','leucoderme','chalk maple', now(), 'Acer leucoderme'),
  ('Acer','macrophyllum','bigleaf maple', now(), 'Acer macrophyllum'),
  ('Acer','negundo','boxelder', now(), 'Acer negundo'),
  ('Acer','nigrum','black maple', now(), 'Acer nigrum'),
  ('Acer','pensylvanicum','striped maple', now(), 'Acer pensylvanicum'),
  ('Acer','rubrum','red maple', now(), 'Acer rubrum'),
  ('Acer','saccharinum','silver maple', now(), 'Acer saccharinum'),
  ('Acer','saccharum','sugar maple', now(), 'Acer saccharum'),
  ('Acer','spicatum','mountain maple', now(), 'Acer spicatum'),
  ('Acoelorrhaphe','wrightii','paurotis palm', now(), 'Acoelorrhaphe wrightii'),
  ('Aesculus','californica','California buckeye', now(), 'Aesculus californica'),
  ('Aesculus','glabra','Ohio buckeye', now(), 'Aesculus glabra'),
  ('Aesculus','octandra','yellow buckeye', now(), 'Aesculus octandra'),
  ('Aesculus','parviflora','bottlebrush buckeye', now(), 'Aesculus parviflora'),
  ('Aesculus','pavia','red buckeye', now(), 'Aesculus pavia'),
  ('Aesculus','sylvatica','painted buckeye', now(), 'Aesculus sylvatica'),
  ('Agave','utahensis','Utah agave', now(), 'Agave utahensis'),
  ('Alnus','maritima','seaside alder', now(), 'Alnus maritima'),
  ('Alnus','oblongifolia','Arizona alder', now(), 'Alnus oblongifolia'),
  ('Alnus','rhombifolia','white alder', now(), 'Alnus rhombifolia'),
  ('Alnus','rubra','red alder', now(), 'Alnus rubra'),
  ('Alnus','rugosa','speckled alder', now(), 'Alnus rugosa'),
  ('Alnus','serrulata','hazel alder', now(), 'Alnus serrulata'),
  ('Alnus','sinuata','Sitka alder', now(), 'Alnus sinuata'),
  ('Alnus','tenuifolia','thinleaf alder', now(), 'Alnus tenuifolia'),
  ('Alvaradoa','amorphoides','Mexican alvaradoa', now(), 'Alvaradoa amorphoides'),
  ('Amelanchier','alnifolia','western serviceberry', now(), 'Amelanchier alnifolia'),
  ('Amelanchier','arborea','downy serviceberry', now(), 'Amelanchier arborea'),
  ('Amelanchier','interior','inland serviceberry', now(), 'Amelanchier interior'),
  ('Amelanchier','sanguinea','roundleaf serviceberry', now(), 'Amelanchier sanguinea'),
  ('Amelanchier','utahensis','Utah serviceberry', now(), 'Amelanchier utahensis'),
  ('Amphitecna','latifolia','black calabash', now(), 'Amphitecna latifolia '),
  ('Amyris','balsamifera','balsam torchwood', now(), 'Amyris balsamifera'),
  ('Amyris','elemifera','torchwood', now(), 'Amyris elemifera'),
  ('Annona','glabra','pond apple', now(), 'Annona glabra'),
  ('Aralia','spinosa','devils walkingstick', now(), 'Aralia spinosa'),
  ('Arbutus','arizonica','Arizona madrone', now(), 'Arbutus arizonica'),
  ('Arbutus','menziesii','Pacific madrone', now(), 'Arbutus menziesii'),
  ('Arbutus','texana','Texas madrone', now(), 'Arbutus texana'),
  ('Arctostaphylos','pringlei','Pringle manzanita', now(), 'Arctostaphylos pringlei'),
  ('Ardisia','escallonioides','marlberry', now(), 'Ardisia escallonioides'),
  ('Artemisia','tridentata','big sagebrush', now(), 'Artemisia tridentata'),
  ('Asimina','parviflora','smallflower pawpaw', now(), 'Asimina parviflora'),
  ('Asimina','triloba','pawpaw', now(), 'Asimina triloba'),
  ('Avicennia','germinans','black mangrove', now(), 'Avicennia germinans'),
  ('Baccharis','halimifolia','eastern baccharis', now(), 'Baccharis halimifolia'),
  ('Betula','alleghaniensis','yellow birch', now(), 'Betula alleghaniensis'),
  ('Betula','lenta','sweet birch', now(), 'Betula lenta'),
  ('Betula','nana','dwarf birch', now(), 'Betula nana '),
  ('Betula','nigra','river birch', now(), 'Betula nigra'),
  ('Betula','occidentalis','water birch', now(), 'Betula occidentalis'),
  ('Betula','papyrifera','paper birch', now(), 'Betula papyrifera'),
  ('Betula','populifolia','gray birch', now(), 'Betula populifolia'),
  ('Betula','uber','Ashe birch', now(), 'Betula uber'),
  ('Bourreria','ovata','Bahama strongbark', now(), 'Bourreria ovata'),
  ('Bourreria','radula','rough strongbark', now(), 'Bourreria radula'),
  ('Bumelia','celastrina','saffron plum', now(), 'Bumelia celastrina'),
  ('Bumelia','lanuginosa','gum bumelia', now(), 'Bumelia lanuginosa'),
  ('Bumelia','lycioides','buckthorn bumelia', now(), 'Bumelia lycioides'),
  ('Bumelia','tenax','tough bumelia', now(), 'Bumelia tenax'),
  ('Bursera','fagaroides','fragrant bursera', now(), 'Bursera fagaroides'),
  ('Bursera','microphylla','elephanttree', now(), 'Bursera microphylla'),
  ('Bursera','simaruba','gumbo limbo', now(), 'Bursera simaruba'),
  ('Byrsonima','lucida','key byrsonima', now(), 'Byrsonima lucida'),
  ('Caesalpinia','mexicana','Mexican poinciana', now(), 'Caesalpinia mexicana'),
  ('Calyptranthes','pallens','pale lidflower', now(), 'Calyptranthes pallens'),
  ('Calyptranthes','zuzygium','myrtle of the river', now(), 'Calyptranthes zuzygium'),
  ('Canella','winterana','canella', now(), 'Canella winterana'),
  ('Canotia','holacantha','canotia', now(), 'Canotia holacantha'),
  ('Capparis','cynophallophora','Jamaica caper', now(), 'Capparis cynophallophora'),
  ('Capparis','flexuosa','limber caper', now(), 'Capparis flexuosa'),
  ('Carpinus','caroliniana','American hornbeam', now(), 'Carpinus caroliniana'),
  ('Carya','aquatica','water hickory', now(), 'Carya aquatica'),
  ('Carya','cordiformis','bitternut hickory', now(), 'Carya cordiformis'),
  ('Carya','floridana','scrub hickory', now(), 'Carya floridana'),
  ('Carya','glabra','pignut hickory', now(), 'Carya glabra'),
  ('Carya','illinoensis','pecan', now(), 'Carya illinoensis'),
  ('Carya','laciniosa','shellbark hickory', now(), 'Carya laciniosa'),
  ('Carya','myristicaeformis','nutmeg hickory', now(), 'Carya myristicaeformis'),
  ('Carya','ovata','shagbark hickory', now(), 'Carya ovata'),
  ('Carya','pallida','sand hickory', now(), 'Carya pallida'),
  ('Carya','texana','black hickory', now(), 'Carya texana'),
  ('Carya','tomentosa','mockernut hickory', now(), 'Carya tomentosa'),
  ('Castanea','alnifolia','Florida chinkapin', now(), 'Castanea alnifolia'),
  ('Castanea','dentata','American chestnut', now(), 'Castanea dentata'),
  ('Castanea','ozarkensis','Ozark chinkapin', now(), 'Castanea ozarkensis'),
  ('Castanea','pumila','Allegheny chinkapin', now(), 'Castanea pumila'),
  ('Castanopsis','chrysophylla','golden chinkapin', now(), 'Castanopsis chrysophylla'),
  ('Catalpa','bignonioides','southern catalpa', now(), 'Catalpa bignonioides'),
  ('Catalpa','speciosa','northern catalpa', now(), 'Catalpa speciosa'),
  ('Ceanothus','arboreus','feltleaf ceanothus', now(), 'Ceanothus arboreus'),
  ('Ceanothus','spinosus','spiny ceanothus', now(), 'Ceanothus spinosus'),
  ('Ceanothus','thyrsiflorus','blueblossom', now(), 'Ceanothus thyrsiflorus'),
  ('Celtis','laevigata','sugarberry', now(), 'Celtis laevigata'),
  ('Celtis','lindheimeri','Lindheimer hackberry', now(), 'Celtis lindheimeri'),
  ('Celtis','occidentalis','hackberry', now(), 'Celtis occidentalis'),
  ('Celtis','reticulata','netleaf hackberry', now(), 'Celtis reticulata'),
  ('Celtis','tenuifolia','Georgia hackberry', now(), 'Celtis tenuifolia'),
  ('Cephalanthus','occidentalis','common buttonbush', now(), 'Cephalanthus occidentalis'),
  ('Cercidium','floridum','blue paloverde', now(), 'Cercidium floridum'),
  ('Cercidium','macrum','border paloverde', now(), 'Cercidium macrum'),
  ('Cercidium','microphyllum','yellow paloverde', now(), 'Cercidium microphyllum'),
  ('Cercis','canadensis','eastern redbud', now(), 'Cercis canadensis'),
  ('Cercis','occidentalis','California redbud', now(), 'Cercis occidentalis'),
  ('Cercocarpus','betuloides','birchleaf cercocarpus', now(), 'Cercocarpus betuloides'),
  ('Cercocarpus','breviflorus','hairy cercocarpus', now(), 'Cercocarpus breviflorus'),
  ('Cercocarpus','ledifolius','curlleaf cercocarpus', now(), 'Cercocarpus ledifolius'),
  ('Cercocarpus','traskiae','Catalina cercocarpus', now(), 'Cercocarpus traskiae'),
  ('Cereus','giganteus','saguaro', now(), 'Cereus giganteus'),
  ('Cereus','robinii','key tree cactus', now(), 'Cereus robinii'),
  ('Chamaecyparis','lawsoniana','Port Orford cedar', now(), 'Chamaecyparis lawsoniana'),
  ('Chamaecyparis','nootkatensis','Alaska cedar', now(), 'Chamaecyparis nootkatensis'),
  ('Chamaecyparis','thyoides','Atlantic white cedar', now(), 'Chamaecyparis thyoides'),
  ('Chilopsis','linearis','desert willow', now(), 'Chilopsis linearis'),
  ('Chionanthus','virginicus','fringetree', now(), 'Chionanthus virginicus'),
  ('Chrysobalanus','icaco','cocoplum', now(), 'Chrysobalanus icaco'),
  ('Chrysophyllum','oliviforme','satinleaf', now(), 'Chrysophyllum oliviforme '),
  ('Citharexylum','berlandieri','Berlandier fiddlewood', now(), 'Citharexylum berlandieri'),
  ('Citharexylum','fruticosum','Florida fiddlewood', now(), 'Citharexylum fruticosum'),
  ('Cladrastis','kentukea','yellowwood', now(), 'Cladrastis kentukea'),
  ('Clethra','acuminata','cinnamon clethra', now(), 'Clethra acuminata'),
  ('Cliftonia','monophylla','buckwheat tree', now(), 'Cliftonia monophylla'),
  ('Clusia','rosea','Florida clusia', now(), 'Clusia rosea'),
  ('Coccoloba','diversifolia','pigeon plum', now(), 'Coccoloba diversifolia'),
  ('Coccoloba','uvifera','seagrape', now(), 'Coccoloba uvifera'),
  ('Coccothrinax','argentata','Florida silverpalm', now(), 'Coccothrinax argentata'),
  ('Colubrina','arborescens','coffee colubrina ', now(), 'Colubrina arborescens '),
  ('Colubrina','cubensis','Cuba colubrina', now(), 'Colubrina cubensis'),
  ('Colubrina','elliptica','soldierwood', now(), 'Colubrina elliptica'),
  ('Condalia','globosa','bitter condalia', now(), 'Condalia globosa'),
  ('Condalia','hookeri','bluewood', now(), 'Condalia hookeri'),
  ('Conocarpus','erectus','button mangrove', now(), 'Conocarpus erectus'),
  ('Cordia','boissieri','anacahuita', now(), 'Cordia boissieri'),
  ('Cordia','sebestena','Geiger tree', now(), 'Cordia sebestena'),
  ('Cornus','alternifolia','alternate leaf dogwood', now(), 'Cornus alternifolia'),
  ('Cornus','drummondii','roughleaf dogwood', now(), 'Cornus drummondii'),
  ('Cornus','florida','flowering dogwood', now(), 'Cornus florida'),
  ('Cornus','glabrata','brown dogwood', now(), 'Cornus glabrata'),
  ('Cornus','nuttallii','Pacific dogwood', now(), 'Cornus nuttallii'),
  ('Cornus','occidentalis','western dogwood', now(), 'Cornus occidentalis'),
  ('Cornus','racemosa','gray dogwood', now(), 'Cornus racemosa'),
  ('Cornus','rugosa','roundleaf dogwood', now(), 'Cornus rugosa'),
  ('Cornus','sessilis','blackfruit dogwood', now(), 'Cornus sessilis'),
  ('Cornus','stolonifera','red osier dogwood', now(), 'Cornus stolonifera'),
  ('Cornus','stricta','stiffcornel dogwood', now(), 'Cornus stricta'),
  ('Corylus','cornuta','beaked hazel', now(), 'Corylus cornuta'),
  ('Cotinus','obovatus','American smoketree', now(), 'Cotinus obovatus'),
  ('Cowania','mexicana','cliffrose', now(), 'Cowania mexicana'),
  ('Crataegus','chrysocarpa','fireberry hawthorn', now(), 'Crataegus chrysocarpa'),
  ('Crataegus','columbiana','Columbia hawthorn', now(), 'Crataegus columbiana'),
  ('Crataegus','douglasii','black hawthorn', now(), 'Crataegus douglasii'),
  ('Crataegus','erythropoda','Cerro hawthorn', now(), 'Crataegus erythropoda'),
  ('Crataegus','saligna','willow hawthorn', now(), 'Crataegus saligna'),
  ('Crataegus','succulenta','fleshy hawthorn', now(), 'Crataegus succulenta'),
  ('Crataegus','tracyi','Tracy hawthorn', now(), 'Crataegus tracyi'),
  ('Crossopetalum','rhacoma','Florida crossopetalum', now(), 'Crossopetalum rhacoma'),
  ('Cupania','glabra','Florida cupania', now(), 'Cupania glabra'),
  ('Cupressus','arizonica','Arizona cypress', now(), 'Cupressus arizonica'),
  ('Cupressus','bakeri','Modoc cypress', now(), 'Cupressus bakeri'),
  ('Cupressus','goveniana','Gowen cypress', now(), 'Cupressus goveniana'),
  ('Cupressus','guadalupensis','Tecate cypress', now(), 'Cupressus guadalupensis'),
  ('Cupressus','macnabiana','MacNab cypress', now(), 'Cupressus macnabiana'),
  ('Cupressus','macrocarpa','Monterey cypress', now(), 'Cupressus macrocarpa'),
  ('Cupressus','sargentii','Sargent cypress', now(), 'Cupressus sargentii'),
  ('Cyrilla','racemiflora','swamp cyrilla', now(), 'Cyrilla racemiflora'),
  ('Dalea','spinosa','smokethorn', now(), 'Dalea spinosa'),
  ('Diospyros','texana','Texas persimmon', now(), 'Diospyros texana'),
  ('Diospyros','virginiana','common persimmon', now(), 'Diospyros virginiana'),
  ('Dipholis','salicifolia','willow bustic', now(), 'Dipholis salicifolia'),
  ('Dodonaea','viscosa','hopbush', now(), 'Dodonaea viscosa'),
  ('Drypetes','diversifolia','milkbark', now(), 'Drypetes diversifolia'),
  ('Drypetes','lateriflora','Guiana plum', now(), 'Drypetes lateriflora'),
  ('Ehretia','anacua','anaqua', now(), 'Ehretia anacua'),
  ('Elliottia','racemosa','elliottia', now(), 'Elliottia racemosa'),
  ('Erythrina','flabelliformis','southwestern coralbean', now(), 'Erythrina flabelliformis'),
  ('Erythrina','herbacea','eastern coralbean', now(), 'Erythrina herbacea'),
  ('Esenbeckia','berlandieri','Berlandier esenbeckia', now(), 'Esenbeckia berlandieri'),
  ('Eugenia','axillaris','white stopper', now(), 'Eugenia axillaris'),
  ('Eugenia','confusa','redberry stopper ', now(), 'Eugenia confusa'),
  ('Eugenia','foetida','boxleaf stopper', now(), 'Eugenia foetida'),
  ('Eugenia','rhombea','red stopper', now(), 'Eugenia rhombea'),
  ('Euonymus','atropurpureus','eastern wahoo', now(), 'Euonymus atropurpureus'),
  ('Euonymus','occidentalis','western wahoo', now(), 'Euonymus occidentalis'),
  ('Exostema','caribaeum','princewood', now(), 'Exostema caribaeum'),
  ('Exothea','paniculata','inkwood', now(), 'Exothea paniculata '),
  ('Eysenhardtia','polystachya','kidneywood', now(), 'Eysenhardtia polystachya'),
  ('Eysenhardtia','texana','Texas kidneywood', now(), 'Eysenhardtia texana'),
  ('Fagus','grandifolia','American beech', now(), 'Fagus grandifolia'),
  ('Ficus','aurea','Florida strangler fig', now(), 'Ficus aurea'),
  ('Ficus','citrifolia','shortleaf fig', now(), 'Ficus citrifolia'),
  ('Forestiera','acuminata','swamp privet', now(), 'Forestiera acuminata'),
  ('Forestiera','angustifolia','Texas forestiera', now(), 'Forestiera angustifolia'),
  ('Forestiera','phillyreoides','desert olive forestiera', now(), 'Forestiera phillyreoides'),
  ('Forestiera','segregata','Florida privet', now(), 'Forestiera segregata'),
  ('Franklinia','alatamaha','franklinia', now(), 'Franklinia alatamaha'),
  ('Fraxinus','americana','white ash', now(), 'Fraxinus americana'),
  ('Fraxinus','anomala','singleleaf ash', now(), 'Fraxinus anomala'),
  ('Fraxinus','berlandieriana','Berlandier ash', now(), 'Fraxinus berlandieriana'),
  ('Fraxinus','caroliniana','Carolina ash', now(), 'Fraxinus caroliniana'),
  ('Fraxinus','cuspidata','fragrant ash', now(), 'Fraxinus cuspidata'),
  ('Fraxinus','dipetala','two petal ash', now(), 'Fraxinus dipetala'),
  ('Fraxinus','gooddingii','Goodding ash', now(), 'Fraxinus gooddingii'),
  ('Fraxinus','greggii','Gregg ash', now(), 'Fraxinus greggii'),
  ('Fraxinus','latifolia','Oregon ash', now(), 'Fraxinus latifolia'),
  ('Fraxinus','nigra','black ash', now(), 'Fraxinus nigra'),
  ('Fraxinus','papillosa','Chihuahua ash', now(), 'Fraxinus papillosa'),
  ('Fraxinus','pennsylvanica','green ash', now(), 'Fraxinus pennsylvanica'),
  ('Fraxinus','profunda','pumpkin ash', now(), 'Fraxinus profunda'),
  ('Fraxinus','quadrangulata','blue ash', now(), 'Fraxinus quadrangulata'),
  ('Fraxinus','texensis','Texas ash', now(), 'Fraxinus texensis'),
  ('Fraxinus','velutina','velvet ash', now(), 'Fraxinus velutina'),
  ('Fremontodendron','californicum','California fremontia', now(), 'Fremontodendron californicum'),
  ('Fremontodendron','mexicanum','Mexican fremontia', now(), 'Fremontodendron mexicanum'),
  ('Garrya','elliptica','wavyleaf silktassel', now(), 'Garrya elliptica'),
  ('Genipa','clusiifolia','seven year apple', now(), 'Genipa clusiifolia'),
  ('Gleditsia','aquatica','waterlocust', now(), 'Gleditsia aquatica'),
  ('Gleditsia','triacanthos','honeylocust', now(), 'Gleditsia triacanthos'),
  ('Gordonia','lasianthus','loblolly bay', now(), 'Gordonia lasianthus'),
  ('Guaiacum','angustifolium','Texas lignumvitae', now(), 'Guaiacum angustifolium'),
  ('Guaiacum','sanctum','roughbark lignumvitae', now(), 'Guaiacum sanctum'),
  ('Guapira','discolor','blolly', now(), 'Guapira discolor'),
  ('Guettarda','elliptica','elliptic leaf velvetseed', now(), 'Guettarda elliptica'),
  ('Guettarda','scabra','roughleaf velvetseed', now(), 'Guettarda scabra'),
  ('Gyminda','latifolia','falsebox', now(), 'Gyminda latifolia'),
  ('Gymnanthes','lucida','oysterwood', now(), 'Gymnanthes lucida'),
  ('Gymnocladus','dioicus','Kentucky coffeetree', now(), 'Gymnocladus dioicus'),
  ('Halesia','carolina','Carolina silverbell', now(), 'Halesia carolina'),
  ('Halesia','diptera','two wing silverbell', now(), 'Halesia diptera'),
  ('Halesia','parviflora','little silverbell', now(), 'Halesia parviflora'),
  ('Hamamelis','virginiana','witch hazel', now(), 'Hamamelis virginiana'),
  ('Hamelia','patens','scarletbush', now(), 'Hamelia patens'),
  ('Helietta','parvifolia','barreta', now(), 'Helietta parvifolia'),
  ('Hippomane','mancinella','manchineel', now(), 'Hippomane mancinella'),
  ('Holacantha','emoryi','holacantha', now(), 'Holacantha emoryi'),
  ('Hypelate','trifoliata','hypelate', now(), 'Hypelate trifoliata'),
  ('Ilex','ambigua','Carolina holly', now(), 'Ilex ambigua'),
  ('Ilex','amelanchier','sarvis holly', now(), 'Ilex amelanchier'),
  ('Ilex','cassine','dahoon', now(), 'Ilex cassine'),
  ('Ilex','coriacea','large gallberry', now(), 'Ilex coriacea'),
  ('Ilex','decidua','possumhaw', now(), 'Ilex decidua'),
  ('Ilex','krugiana','tawnyberry holly', now(), 'Ilex krugiana'),
  ('Ilex','laevigata','smooth winterberry', now(), 'Ilex laevigata'),
  ('Ilex','longipes','Georgia holly', now(), 'Ilex longipes'),
  ('Ilex','montana','mountain winterberry', now(), 'Ilex montana'),
  ('Ilex','myrtifolia','myrtle dahoon', now(), 'Ilex myrtifolia'),
  ('Ilex','opaca','American holly', now(), 'Ilex opaca'),
  ('Ilex','verticillata','common winterberry', now(), 'Ilex verticillata'),
  ('Ilex','vomitoria','yaupon', now(), 'Ilex vomitoria'),
  ('Illicium','floridanum','Florida anise tree', now(), 'Illicium floridanum'),
  ('Illicium','parviflorum','yellow anise tree', now(), 'Illicium parviflorum'),
  ('Jacquinia','keyensis','joewood', now(), 'Jacquinia keyensis'),
  ('Juglans','californica','California walnut', now(), 'Juglans californica'),
  ('Juglans','cinerea','butternut', now(), 'Juglans cinerea'),
  ('Juglans','hindsii','Hinds walnut', now(), 'Juglans hindsii'),
  ('Juglans','major','Arizona walnut', now(), 'Juglans major'),
  ('Juglans','microcarpa','little walnut', now(), 'Juglans microcarpa'),
  ('Juglans','nigra','black walnut', now(), 'Juglans nigra'),
  ('Juniperus','ashei','Ashe juniper', now(), 'Juniperus ashei'),
  ('Juniperus','californica','California juniper', now(), 'Juniperus californica'),
  ('Juniperus','communis','common juniper', now(), 'Juniperus communis'),
  ('Juniperus','deppeana','alligator juniper', now(), 'Juniperus deppeana'),
  ('Juniperus','erythrocarpa','redberry juniper', now(), 'Juniperus erythrocarpa'),
  ('Juniperus','flaccida','drooping juniper', now(), 'Juniperus flaccida'),
  ('Juniperus','horizontalis','creeping juniper', now(), 'Juniperus horizontalis'),
  ('Juniperus','monosperma','one seed juniper', now(), 'Juniperus monosperma'),
  ('Juniperus','occidentalis','western juniper', now(), 'Juniperus occidentalis'),
  ('Juniperus','osteosperma','Utah juniper', now(), 'Juniperus osteosperma'),
  ('Juniperus','pinchotii','Pinchot juniper', now(), 'Juniperus pinchotii'),
  ('Juniperus','scopulorum','Rocky Mountain juniper', now(), 'Juniperus scopulorum'),
  ('Juniperus','silicicola','southern redcedar', now(), 'Juniperus silicicola'),
  ('Juniperus','virginiana','eastern redcedar', now(), 'Juniperus virginiana'),
  ('Kalmia','latifolia','mountain laurel', now(), 'Kalmia latifolia'),
  ('Koeberlinia','spinosa','allthorn', now(), 'Koeberlinia spinosa'),
  ('Krugiodendron','ferreum','leadwood', now(), 'Krugiodendron ferreum'),
  ('Laguncularia','racemosa','white mangrove', now(), 'Laguncularia racemosa'),
  ('Larix','laricina','tamarack', now(), 'Larix laricina'),
  ('Larix','lyallii','subalpine larch', now(), 'Larix lyallii'),
  ('Larix','occidentalis','western larch', now(), 'Larix occidentalis'),
  ('Larrea','divaricata','creosote bush', now(), 'Larrea divaricata'),
  ('Leitneria','floridana','corkwood', now(), 'Leitneria floridana'),
  ('Leucaena','pulverulenta','great leadtree', now(), 'Leucaena pulverulenta'),
  ('Leucaena','retusa','littleleaf leadtree', now(), 'Leucaena retusa'),
  ('Libocedrus','decurrens','incense cedar', now(), 'Libocedrus decurrens'),
  ('Licaria','triandra','Florida licaria', now(), 'Licaria triandra '),
  ('Liquidambar','styraciflua','sweetgum', now(), 'Liquidambar styraciflua'),
  ('Liriodendron','tulipifera','yellow poplar', now(), 'Liriodendron tulipifera'),
  ('Lithocarpus','densiflorus','tanoak', now(), 'Lithocarpus densiflorus'),
  ('Lyonia','ferruginea','tree lyonia', now(), 'Lyonia ferruginea'),
  ('Lyonothamnus','floribundus','Lyontree', now(), 'Lyonothamnus floribundus'),
  ('Lysiloma','latisiliquum','Bahama lysiloma', now(), 'Lysiloma latisiliquum'),
  ('Lysiloma','microphylla','littleleaf lysiloma', now(), 'Lysiloma microphylla'),
  ('Maclura','pomifera','Osage orange', now(), 'Maclura pomifera'),
  ('Magnolia','acuminata','cucumbertree', now(), 'Magnolia acuminata'),
  ('Magnolia','ashei','Ashe magnolia', now(), 'Magnolia ashei'),
  ('Magnolia','fraseri','Fraser magnolia', now(), 'Magnolia fraseri'),
  ('Magnolia','grandiflora','southern magnolia', now(), 'Magnolia grandiflora'),
  ('Magnolia','macrophylla','bigleaf magnolia', now(), 'Magnolia macrophylla'),
  ('Magnolia','pyramidata','pyramid magnolia', now(), 'Magnolia pyramidata'),
  ('Magnolia','tripetala','umbrella magnolia', now(), 'Magnolia tripetala'),
  ('Magnolia','virginiana','sweetbay', now(), 'Magnolia virginiana'),
  ('Malus','angustifolia','southern crab apple', now(), 'Malus angustifolia'),
  ('Malus','coronaria','sweet crab apple', now(), 'Malus coronaria'),
  ('Malus','diversifolia','Oregon crab apple', now(), 'Malus diversifolia'),
  ('Malus','ioensis','prairie crab apple', now(), 'Malus ioensis'),
  ('Manilkara','bahamensis','wild dilly', now(), 'Manilkara bahamensis'),
  ('Mastichodendron','foetidissimum','false mastic', now(), 'Mastichodendron foetidissimum'),
  ('Maytenus','phyllanthoides','Florida mayten', now(), 'Maytenus phyllanthoides'),
  ('Metopium','toxiferum','Florida poisontree', now(), 'Metopium toxiferum'),
  ('Morus','microphylla','Texas mulberry', now(), 'Morus microphylla'),
  ('Morus','rubra','red mulberry', now(), 'Morus rubra'),
  ('Myrcianthes','fragrans','twinberry stopper', now(), 'Myrcianthes fragrans'),
  ('Myrica','californica','Pacific bayberry', now(), 'Myrica californica'),
  ('Myrica','cerifera','southern bayberry', now(), 'Myrica cerifera'),
  ('Myrica','heterophylla','evergreen bayberry', now(), 'Myrica heterophylla'),
  ('Myrica','inodora','odorless bayberry', now(), 'Myrica inodora'),
  ('Myrica','pensylvanica','northern bayberry', now(), 'Myrica pensylvanica'),
  ('Nectandra','coriacea','Florida nectandra', now(), 'Nectandra coriacea'),
  ('Nemopanthus','collinus','mountain holly', now(), 'Nemopanthus collinus'),
  ('Nolina','bigelovii','Bigelow nolina', now(), 'Nolina bigelovii'),
  ('Nyssa','aquatica','water tupelo', now(), 'Nyssa aquatica'),
  ('Nyssa','ogeche','Ogeechee tupelo', now(), 'Nyssa ogeche'),
  ('Nyssa','sylvatica','black tupelo, blackgum', now(), 'Nyssa sylvatica'),
  ('Olneya','tesota','tesota', now(), 'Olneya tesota'),
  ('Opuntia','fulgida','jumping cholla', now(), 'Opuntia fulgida'),
  ('Osmanthus','americanus','devilwood', now(), 'Osmanthus americanus'),
  ('Ostrya','chisosensis','Chisos hophornbean', now(), 'Ostrya chisosensis'),
  ('Ostrya','knowltonii','Knowlton hophornbeam', now(), 'Ostrya knowltonii'),
  ('Ostrya','virginiana','eastern hophornbeam', now(), 'Ostrya virginiana'),
  ('Oxydendrum','arboreum','sourwood', now(), 'Oxydendrum arboreum'),
  ('Parkinsonia','aculeata','Jerusalem thorn', now(), 'Parkinsonia aculeata'),
  ('Persea','borbonia','redbay', now(), 'Persea borbonia'),
  ('Photinia','arbutifolia','Christmas berry', now(), 'Photinia arbutifolia'),
  ('Picea','breweriana','Brewer spruce', now(), 'Picea breweriana'),
  ('Picea','chihuahuana','chihuahua spruce', now(), 'Picea chihuahuana'),
  ('Picea','engelmannii','Engelmann spruce', now(), 'Picea engelmannii'),
  ('Picea','glauca','white spruce', now(), 'Picea glauca'),
  ('Picea','mariana','black spruce', now(), 'Picea mariana'),
  ('Picea','pungens','blue spruce', now(), 'Picea pungens'),
  ('Picea','rubens','red spruce', now(), 'Picea rubens'),
  ('Picea','sitchensis','Sitka spruce', now(), 'Picea sitchensis'),
  ('Picramnia','pentandra','bitterbush', now(), 'Picramnia pentandra '),
  ('Pinckneya','pubens','pinckneya', now(), 'Pinckneya pubens'),
  ('Pinus','albicaulis','whitebark pine', now(), 'Pinus albicaulis'),
  ('Pinus','aristata','bristlecone pine', now(), 'Pinus aristata'),
  ('Pinus','attenuata','knobcone pine', now(), 'Pinus attenuata'),
  ('Pinus','ayacahuite','Mexican white pine', now(), 'Pinus ayacahuite'),
  ('Pinus','balfouriana','foxtail pine', now(), 'Pinus balfouriana'),
  ('Pinus','banksiana','jack pine', now(), 'Pinus banksiana'),
  ('Pinus','caribaea','Caribbean pine', now(), 'Pinus caribaea'),
  ('Pinus','cembroides','Mexican pinyon', now(), 'Pinus cembroides'),
  ('Pinus','clausa','sand pine', now(), 'Pinus clausa'),
  ('Pinus','contorta','lodgepole pine', now(), 'Pinus contorta'),
  ('Pinus','cooperi','Cooper pine', now(), 'Pinus cooperi'),
  ('Pinus','coulteri','Coulter pine', now(), 'Pinus coulteri'),
  ('Pinus','cubensis','Cuban pine', now(), 'Pinus cubensis'),
  ('Pinus','culminicola','Potosi pinyon', now(), 'Pinus culminicola'),
  ('Pinus','douglasiana','Douglas pine', now(), 'Pinus douglasiana'),
  ('Pinus','durangensis','Durango pine', now(), 'Pinus durangensis'),
  ('Pinus','echinata','shortleaf pine', now(), 'Pinus echinata'),
  ('Pinus','edulis','pinyon', now(), 'Pinus edulis'),
  ('Pinus','elliottii','slash pine', now(), 'Pinus elliottii'),
  ('Pinus','engelmannii','Apache pine', now(), 'Pinus engelmannii'),
  ('Pinus','flexilis','limber pine', now(), 'Pinus flexilis'),
  ('Pinus','glabra','spruce pine', now(), 'Pinus glabra'),
  ('Pinus','greggii','Gregg pine', now(), 'Pinus greggii'),
  ('Pinus','hartwegii','Hartweg pine', now(), 'Pinus hartwegii'),
  ('Pinus','jeffreyi','Jeffrey pine', now(), 'Pinus jeffreyi'),
  ('Pinus','lambertiana','sugar pine', now(), 'Pinus lambertiana'),
  ('Pinus','lawsonii','Lawson pine', now(), 'Pinus lawsonii'),
  ('Pinus','leiophylla','Chihuahua pine', now(), 'Pinus leiophylla'),
  ('Pinus','longaeva','Intermountain bristlecone pine', now(), 'Pinus longaeva '),
  ('Pinus','lumholtzii','Lumholtz pine', now(), 'Pinus lumholtzii'),
  ('Pinus','maximartinezii','Mart?nez pinyon', now(), 'Pinus maximartinezii'),
  ('Pinus','michoacana','Michoacßn pine', now(), 'Pinus michoacana'),
  ('Pinus','monophylla','singleleaf pinyon', now(), 'Pinus monophylla'),
  ('Pinus','montezumae','Montezuma pine', now(), 'Pinus montezumae'),
  ('Pinus','monticola','western white pine', now(), 'Pinus monticola'),
  ('Pinus','muricata','bishop pine', now(), 'Pinus muricata'),
  ('Pinus','nelsonii','Nelson pinyon', now(), 'Pinus nelsonii'),
  ('Pinus','occidentalis','West Indian pine', now(), 'Pinus occidentalis'),
  ('Pinus','oocarpa','Nicaraguan pitch pine; ocote pine', now(), 'Pinus oocarpa'),
  ('Pinus','palustris','longleaf pine', now(), 'Pinus palustris'),
  ('Pinus','patula','Mexican weeping pine', now(), 'Pinus patula'),
  ('Pinus','pinceana','Pince pinyon', now(), 'Pinus pinceana'),
  ('Pinus','ponderosa','ponderosa pine', now(), 'Pinus ponderosa'),
  ('Pinus','pringlei','Pringle pine', now(), 'Pinus pringlei'),
  ('Pinus','pseudostrobus','False Weymouth pine', now(), 'Pinus pseudostrobus'),
  ('Pinus','pungens','Table Mountain pine', now(), 'Pinus pungens'),
  ('Pinus','quadrifolia','Parry pinyon', now(), 'Pinus quadrifolia'),
  ('Pinus','radiata','Monterey pine', now(), 'Pinus radiata'),
  ('Pinus','resinosa','red pine', now(), 'Pinus resinosa'),
  ('Pinus','rigida','pitch pine', now(), 'Pinus rigida'),
  ('Pinus','sabiniana','Digger pine', now(), 'Pinus sabiniana'),
  ('Pinus','serotina','pond pine', now(), 'Pinus serotina'),
  ('Pinus','strobiformis','southwestern white pine', now(), 'Pinus strobiformis'),
  ('Pinus','strobus','eastern white pine', now(), 'Pinus strobus'),
  ('Pinus','taeda','loblolly pine', now(), 'Pinus taeda'),
  ('Pinus','teocote','Twisted  leaves pine; Aztec pine', now(), 'Pinus teocote'),
  ('Pinus','torreyana','Torrey pine', now(), 'Pinus torreyana'),
  ('Pinus','tropicalis','tropical pine', now(), 'Pinus tropicalis'),
  ('Pinus','virginiana','Virginia pine', now(), 'Pinus virginiana'),
  ('Pinus','washoensis','Washoe pine', now(), 'Pinus washoensis'),
  ('Piscidia','piscipula','Florida fishpoison tree', now(), 'Piscidia piscipula'),
  ('Pisonia','rotundata','pisonia', now(), 'Pisonia rotundata'),
  ('Pistacia','texana','Texas pistache', now(), 'Pistacia texana'),
  ('Pithecellobium','flexicaule','ebony blackbead', now(), 'Pithecellobium flexicaule'),
  ('Pithecellobium','guadalupense','Guadeloupe blackbead', now(), 'Pithecellobium guadalupense'),
  ('Pithecellobium','pallens','huajillo', now(), 'Pithecellobium pallens'),
  ('Pithecellobium','unguis-cati','catclaw blackbead', now(), 'Pithecellobium unguis-cati'),
  ('Planera','aquatica','planertree', now(), 'Planera aquatica'),
  ('Platanus','occidentalis','American sycamore', now(), 'Platanus occidentalis'),
  ('Platanus','racemosa','California sycamore', now(), 'Platanus racemosa'),
  ('Platanus','wrightii','Arizona sycamore', now(), 'Platanus wrightii'),
  ('Populus','angustifolia','narrowleaf cottonwood', now(), 'Populus angustifolia'),
  ('Populus','arizonica','Arizona cottonwood', now(), 'Populus arizonica'),
  ('Populus','balsamifera','balsam poplar', now(), 'Populus balsamifera'),
  ('Populus','deltoides','eastern cottonwood', now(), 'Populus deltoides'),
  ('Populus','fremontii','Fremont cottonwood', now(), 'Populus fremontii'),
  ('Populus','grandidentata','bigtooth aspen', now(), 'Populus grandidentata'),
  ('Populus','heterophylla','swamp cottonwood', now(), 'Populus heterophylla'),
  ('Populus','hinckleyana','Hinckley cottonwood', now(), 'Populus hinckleyana'),
  ('Populus','tremuloides','quaking aspen', now(), 'Populus tremuloides'),
  ('Populus','trichocarpa','black cottonwood', now(), 'Populus trichocarpa'),
  ('Prosopis','juliflora','mesquite', now(), 'Prosopis juliflora'),
  ('Prosopis','pubescens','screwbean mesquite', now(), 'Prosopis pubescens'),
  ('Prunus','alleghaniensis','Allegheny plum', now(), 'Prunus alleghaniensis'),
  ('Prunus','americana','American plum', now(), 'Prunus americana'),
  ('Prunus','angustifolia','Chickasaw plum', now(), 'Prunus angustifolia'),
  ('Prunus','caroliniana','Carolina laurelcherry', now(), 'Prunus caroliniana'),
  ('Prunus','emarginata','bitter cherry', now(), 'Prunus emarginata'),
  ('Prunus','fremontii','desert apricot', now(), 'Prunus fremontii'),
  ('Prunus','hortulana','hortulan plum', now(), 'Prunus hortulana'),
  ('Prunus','ilicifolia','hollyleaf cherry', now(), 'Prunus ilicifolia'),
  ('Prunus','lyonii','Catalina cherry', now(), 'Prunus lyonii'),
  ('Prunus','mexicana','Mexican plum', now(), 'Prunus mexicana'),
  ('Prunus','munsoniana','wildgoose plum', now(), 'Prunus munsoniana'),
  ('Prunus','myrtifolia','West Indies cherry', now(), 'Prunus myrtifolia'),
  ('Prunus','nigra','Canada plum', now(), 'Prunus nigra'),
  ('Prunus','pensylvanica','pin cherry', now(), 'Prunus pensylvanica'),
  ('Prunus','serotina','black cherry', now(), 'Prunus serotina'),
  ('Prunus','subcordata','Klamath plum', now(), 'Prunus subcordata'),
  ('Prunus','umbellata','flatwoods plum', now(), 'Prunus umbellata'),
  ('Prunus','virginiana','common chokecherry', now(), 'Prunus virginiana'),
  ('Pseudophoenix','sargentii','buccaneer palm', now(), 'Pseudophoenix sargentii'),
  ('Pseudotsuga','macrocarpa','bigcone Douglas fir', now(), 'Pseudotsuga macrocarpa'),
  ('Pseudotsuga','menziesii','Douglas fir', now(), 'Pseudotsuga menziesii'),
  ('Psidium','longipes','long stalk stopper', now(), 'Psidium longipes'),
  ('Ptelea','crenulata','California hoptree', now(), 'Ptelea crenulata'),
  ('Ptelea','trifoliata','common hoptree', now(), 'Ptelea trifoliata'),
  ('Quercus','agrifolia','California live oak', now(), 'Quercus agrifolia'),
  ('Quercus','ajoensis','Ajo oak', now(), 'Quercus ajoensis'),
  ('Quercus','alba','white oak', now(), 'Quercus alba'),
  ('Quercus','arizonica','Arizona white oak', now(), 'Quercus arizonica'),
  ('Quercus','arkansana','Arkansas oak', now(), 'Quercus arkansana'),
  ('Quercus','bicolor','swamp white oak', now(), 'Quercus bicolor'),
  ('Quercus','chapmanii','Chapman oak', now(), 'Quercus chapmanii'),
  ('Quercus','chrysolepis','canyon live oak', now(), 'Quercus chrysolepis'),
  ('Quercus','coccinea','scarlet oak', now(), 'Quercus coccinea'),
  ('Quercus','douglasii','blue oak', now(), 'Quercus douglasii'),
  ('Quercus','dunnii','Dunn oak', now(), 'Quercus dunnii'),
  ('Quercus','durandii','Durand oak', now(), 'Quercus durandii'),
  ('Quercus','ellipsoidalis','northern pin oak', now(), 'Quercus ellipsoidalis'),
  ('Quercus','emoryi','Emory oak', now(), 'Quercus emoryi'),
  ('Quercus','engelmannii','Engelmann oak', now(), 'Quercus engelmannii'),
  ('Quercus','falcata','southern red oak', now(), 'Quercus falcata'),
  ('Quercus','gambelii','Gambel oak', now(), 'Quercus gambelii'),
  ('Quercus','garryana','Oregon white oak', now(), 'Quercus garryana'),
  ('Quercus','georgiana','Georgia oak', now(), 'Quercus georgiana'),
  ('Quercus','glaucoides','Lacey oak', now(), 'Quercus glaucoides'),
  ('Quercus','graciliformis','Chisos oak', now(), 'Quercus graciliformis'),
  ('Quercus','gravesii','Graves oak incl. Q. tardifolia (Muller) lateleaf oak', now(), 'Quercus gravesii'),
  ('Quercus','grisea','gray oak', now(), 'Quercus grisea'),
  ('Quercus','havardii','Havard oak', now(), 'Quercus havardii'),
  ('Quercus','hypoleucoides','silverleaf oak', now(), 'Quercus hypoleucoides'),
  ('Quercus','ilicifolia','bear oak', now(), 'Quercus ilicifolia'),
  ('Quercus','imbricaria','shingle oak', now(), 'Quercus imbricaria'),
  ('Quercus','incana','bluejack oak', now(), 'Quercus incana'),
  ('Quercus','kelloggii','California black oak', now(), 'Quercus kelloggii'),
  ('Quercus','laevis','turkey oak', now(), 'Quercus laevis'),
  ('Quercus','laurifolia','laurel oak', now(), 'Quercus laurifolia'),
  ('Quercus','lobata','California white oak', now(), 'Quercus lobata'),
  ('Quercus','lyrata','overcup oak', now(), 'Quercus lyrata'),
  ('Quercus','macdonaldii','McDonald oak', now(), 'Quercus macdonaldii'),
  ('Quercus','macrocarpa','bur oak', now(), 'Quercus macrocarpa'),
  ('Quercus','marilandica','blackjack oak', now(), 'Quercus marilandica'),
  ('Quercus','michauxii','swamp chestnut oak', now(), 'Quercus michauxii'),
  ('Quercus','mohriana','Mohrs oak', now(), 'Quercus mohriana'),
  ('Quercus','muehlenbergii','chinkapin oak', now(), 'Quercus muehlenbergii'),
  ('Quercus','myrtifolia','myrtle oak', now(), 'Quercus myrtifolia'),
  ('Quercus','nigra','water oak', now(), 'Quercus nigra'),
  ('Quercus','nuttallii','Nuttall oak', now(), 'Quercus nuttallii'),
  ('Quercus','oblongifolia','Mexican blue oak', now(), 'Quercus oblongifolia'),
  ('Quercus','oglethorpensis','Oglethorpe oak', now(), 'Quercus oglethorpensis'),
  ('Quercus','palustris','pin oak', now(), 'Quercus palustris'),
  ('Quercus','phellos','willow oak', now(), 'Quercus phellos'),
  ('Quercus','prinus','chestnut oak', now(), 'Quercus prinus'),
  ('Quercus','pungens','sandpaper oak', now(), 'Quercus pungens'),
  ('Quercus','rubra','northern red oak', now(), 'Quercus rubra'),
  ('Quercus','rugosa','netleaf oak', now(), 'Quercus rugosa'),
  ('Quercus','shumardii','Shumard oak', now(), 'Quercus shumardii'),
  ('Quercus','stellata','post oak', now(), 'Quercus stellata'),
  ('Quercus','tomentella','island live oak', now(), 'Quercus tomentella'),
  ('Quercus','toumeyi','Toumey oak', now(), 'Quercus toumeyi'),
  ('Quercus','turbinella','shrub live oak', now(), 'Quercus turbinella'),
  ('Quercus','velutina','black oak', now(), 'Quercus velutina'),
  ('Quercus','virginiana','live oak', now(), 'Quercus virginiana'),
  ('Quercus','wislizeni','interior live oak', now(), 'Quercus wislizeni'),
  ('Rapanea','punctata','Florida rapanea', now(), 'Rapanea punctata'),
  ('Reynosia','septentrionalis','darling plum', now(), 'Reynosia septentrionalis'),
  ('Rhamnus','betulaefolia','birchleaf buckthorn', now(), 'Rhamnus betulaefolia'),
  ('Rhamnus','californica','California buckthorn', now(), 'Rhamnus californica'),
  ('Rhamnus','caroliniana','Carolina buckthorn', now(), 'Rhamnus caroliniana'),
  ('Rhamnus','crocea','hollyleaf buckthorn', now(), 'Rhamnus crocea'),
  ('Rhamnus','purshiana','cascara buckthorn', now(), 'Rhamnus purshiana'),
  ('Rhizophora','mangle','mangrove', now(), 'Rhizophora mangle'),
  ('Rhododendron','catawbiense','Catawba rhododendron', now(), 'Rhododendron catawbiense'),
  ('Rhododendron','macrophyllum','Pacific rhododendron', now(), 'Rhododendron macrophyllum'),
  ('Rhododendron','maximum','rosebay rhododendron', now(), 'Rhododendron maximum'),
  ('Rhus','choriophylla','Mearns sumac', now(), 'Rhus choriophylla'),
  ('Rhus','copallina','shining sumac', now(), 'Rhus copallina'),
  ('Rhus','glabra','smooth sumac', now(), 'Rhus glabra'),
  ('Rhus','integrifolia','lemonade sumac', now(), 'Rhus integrifolia'),
  ('Rhus','kearneyi','Kearney sumac', now(), 'Rhus kearneyi'),
  ('Rhus','lanceolata','prairie sumac', now(), 'Rhus lanceolata'),
  ('Rhus','laurina','laurel sumac', now(), 'Rhus laurina'),
  ('Rhus','microphylla','littleleaf sumac', now(), 'Rhus microphylla'),
  ('Rhus','ovata','sugar sumac', now(), 'Rhus ovata'),
  ('Rhus','typhina','staghorn sumac', now(), 'Rhus typhina'),
  ('Robinia','kelseyi','Kelsey locust', now(), 'Robinia kelseyi'),
  ('Robinia','neomexicana','New Mexican locust', now(), 'Robinia neomexicana'),
  ('Robinia','pseudoacacia','black locust', now(), 'Robinia pseudoacacia'),
  ('Robinia','viscosa','clammy locust', now(), 'Robinia viscosa'),
  ('Roystonea','elata','Florida royalpalm', now(), 'Roystonea elata'),
  ('Sabal','mexicana','Mexican palmetto', now(), 'Sabal mexicana'),
  ('Sabal','minor','dwarf palmetto', now(), 'Sabal minor'),
  ('Sabal','palmetto','cabbage palmetto', now(), 'Sabal palmetto'),
  ('Salix','alaxensis','feltleaf willow', now(), 'Salix alaxensis'),
  ('Salix','amygdaloides','peachleaf willow', now(), 'Salix amygdaloides'),
  ('Salix','arbusculoides','peachleaf willow', now(), 'Salix arbusculoides'),
  ('Salix','bebbiana','Bebb willow', now(), 'Salix bebbiana'),
  ('Salix','bonplandiana','Bonpland willow', now(), 'Salix bonplandiana'),
  ('Salix','caroliniana','Coastal Plain willow', now(), 'Salix caroliniana'),
  ('Salix','discolor','pussy willow', now(), 'Salix discolor'),
  ('Salix','exigua','coyote willow', now(), 'Salix exigua'),
  ('Salix','floridana','Florida willow', now(), 'Salix floridana'),
  ('Salix','fluviatilis','river willow', now(), 'Salix fluviatilis'),
  ('Salix','geyeriana','Geyer willow', now(), 'Salix geyeriana'),
  ('Salix','hindsiana','Hinds willow', now(), 'Salix hindsiana'),
  ('Salix','hookeriana','Hooker willow', now(), 'Salix hookeriana'),
  ('Salix','laevigata','red willow', now(), 'Salix laevigata'),
  ('Salix','lasiandra','Pacific willow', now(), 'Salix lasiandra'),
  ('Salix','lasiolepis','arroyo willow', now(), 'Salix lasiolepis'),
  ('Salix','lucida','shining willow', now(), 'Salix lucida'),
  ('Salix','mackenzieana','Mackenzie willow', now(), 'Salix mackenzieana'),
  ('Salix','nigra','black willow', now(), 'Salix nigra'),
  ('Salix','pellita','satiny willow', now(), 'Salix pellita'),
  ('Salix','petiolaris','meadow willow', now(), 'Salix petiolaris'),
  ('Salix','pyrifolia','balsam willow', now(), 'Salix pyrifolia'),
  ('Salix','scouleriana','Scouler willow', now(), 'Salix scouleriana'),
  ('Salix','sericea','silky willow', now(), 'Salix sericea'),
  ('Salix','sessilifolia','northwest willow', now(), 'Salix sessilifolia'),
  ('Salix','sitchensis','Sitka willow', now(), 'Salix sitchensis'),
  ('Salix','taxifolia','yewleaf willow', now(), 'Salix taxifolia'),
  ('Salix','tracyi','Tracy willow', now(), 'Salix tracyi'),
  ('Sambucus','callicarpa','Pacific red elder', now(), 'Sambucus callicarpa'),
  ('Sambucus','canadensis','American elder', now(), 'Sambucus canadensis'),
  ('Sambucus','glauca','blueberry elder', now(), 'Sambucus glauca'),
  ('Sambucus','melanocarpa','blackbead elder', now(), 'Sambucus melanocarpa'),
  ('Sambucus','mexicana','Mexican elder', now(), 'Sambucus mexicana'),
  ('Sambucus','velutina','velvet elder', now(), 'Sambucus velutina'),
  ('Sapindus','drummondii','western soapberry', now(), 'Sapindus drummondii'),
  ('Sapindus','saponaria','wingleaf soapberry', now(), 'Sapindus saponaria'),
  ('Sapium','biloculare','jumping bean sapium', now(), 'Sapium biloculare'),
  ('Sassafras','albidum','sassafras', now(), 'Sassafras albidum'),
  ('Savia','bahamensis','maidenbush', now(), 'Savia bahamensis'),
  ('Schaefferia','frutescens','Florida boxwood', now(), 'Schaefferia frutescens'),
  ('Schoepfia','chrysophylloides','graytwig', now(), 'Schoepfia chrysophylloides'),
  ('Sequoia','sempervirens','redwood', now(), 'Sequoia sempervirens'),
  ('Sequoiadendron','giganteum','giant sequoia', now(), 'Sequoiadendron giganteum'),
  ('Serenoa','repens','saw palmetto', now(), 'Serenoa repens'),
  ('Shepherdia','argentea','silver buffaloberry', now(), 'Shepherdia argentea'),
  ('Simarouba','glauca','paradise tree', now(), 'Simarouba glauca'),
  ('Solanum','erianthum','mullein nightshade', now(), 'Solanum erianthum'),
  ('Sophora','affinis','Texas sophora', now(), 'Sophora affinis'),
  ('Sophora','secundiflora','mescalbean', now(), 'Sophora secundiflora'),
  ('Sorbus','americana','American mountain ash', now(), 'Sorbus americana'),
  ('Sorbus','decora','showy mountain ash', now(), 'Sorbus decora'),
  ('Sorbus','scopulina','Greene mountain ash', now(), 'Sorbus scopulina'),
  ('Sorbus','sitchensis','Sitka mountain ash', now(), 'Sorbus sitchensis'),
  ('Staphylea','bolanderi','Sierra bladdernut', now(), 'Staphylea bolanderi'),
  ('Staphylea','trifolia','American bladdernut', now(), 'Staphylea trifolia'),
  ('Stewartia','malacodendron','Virginia stewartia', now(), 'Stewartia malacodendron'),
  ('Stewartia','ovata','mountain stewartia', now(), 'Stewartia ovata'),
  ('Styrax','americana','American snowbell', now(), 'Styrax americana'),
  ('Styrax','grandifolia','bigleaf snowbell', now(), 'Styrax grandifolia'),
  ('Styrax','platanifolia','sycamore leaf snowbell', now(), 'Styrax platanifolia'),
  ('Suriana','maritima','baycedar', now(), 'Suriana maritima'),
  ('Swietenia','mahagoni','West Indies mahogany', now(), 'Swietenia mahagoni'),
  ('Symplocos','tinctoria','common sweetleaf', now(), 'Symplocos tinctoria'),
  ('Taxodium','distichum','baldcypress', now(), 'Taxodium distichum'),
  ('Taxodium','mucronatum','Montezuma baldcypress', now(), 'Taxodium mucronatum'),
  ('Taxus','brevifolia','Pacific yew', now(), 'Taxus brevifolia'),
  ('Taxus','canadensis','Canada yew', now(), 'Taxus canadensis'),
  ('Taxus','floridana','Florida yew', now(), 'Taxus floridana'),
  ('Tetrazygia','bicolor','Florida tetrazygia', now(), 'Tetrazygia bicolor'),
  ('Thrinax','morrisii','key thatchpalm', now(), 'Thrinax morrisii'),
  ('Thrinax','radiata','Florida thatchpalm', now(), 'Thrinax radiata'),
  ('Thuja','occidentalis','northern white cedar', now(), 'Thuja occidentalis'),
  ('Thuja','plicata','western redcedar', now(), 'Thuja plicata'),
  ('Tilia','americana','American basswood', now(), 'Tilia americana'),
  ('Tilia','caroliniana','Carolina basswood', now(), 'Tilia caroliniana'),
  ('Tilia','heterophylla','white basswood', now(), 'Tilia heterophylla'),
  ('Torreya','californica','California torreya', now(), 'Torreya californica'),
  ('Torreya','taxifolia','Florida torreya', now(), 'Torreya taxifolia'),
  ('Toxicodendron','vernix','poison sumac', now(), 'Toxicodendron vernix'),
  ('Trema','lamarckiana','West Indies trema', now(), 'Trema lamarckiana'),
  ('Trema','micrantha','Florida trema', now(), 'Trema micrantha'),
  ('Tsuga','canadensis','eastern hemlock', now(), 'Tsuga canadensis'),
  ('Tsuga','caroliniana','Carolina hemlock', now(), 'Tsuga caroliniana'),
  ('Tsuga','heterophylla','western hemlock', now(), 'Tsuga heterophylla'),
  ('Tsuga','mertensiana','mountain hemlock', now(), 'Tsuga mertensiana'),
  ('Ulmus','alata','winged elm', now(), 'Ulmus alata'),
  ('Ulmus','americana','American elm', now(), 'Ulmus americana'),
  ('Ulmus','crassifolia','cedar elm', now(), 'Ulmus crassifolia'),
  ('Ulmus','rubra','slippery elm', now(), 'Ulmus rubra'),
  ('Ulmus','serotina','September elm', now(), 'Ulmus serotina'),
  ('Ulmus','thomasii','rock elm', now(), 'Ulmus thomasii'),
  ('Umbellularia','californica','California laurel', now(), 'Umbellularia californica'),
  ('Ungnadia','speciosa','Mexican buckeye', now(), 'Ungnadia speciosa'),
  ('Vaccinium','arboreum','tree sparkleberry', now(), 'Vaccinium arboreum'),
  ('Vauquelinia','californica','Torrey vauquelinia', now(), 'Vauquelinia californica'),
  ('Vauquelinia','pauciflora','fewflower vauquelinia', now(), 'Vauquelinia pauciflora'),
  ('Viburnum','lentago','nannyberry', now(), 'Viburnum lentago'),
  ('Viburnum','nudum','possumhaw viburnum', now(), 'Viburnum nudum'),
  ('Viburnum','obovatum','Walter viburnum', now(), 'Viburnum obovatum'),
  ('Viburnum','prunifolium','blackhaw', now(), 'Viburnum prunifolium'),
  ('Viburnum','rufidulum','rusty blackhaw', now(), 'Viburnum rufidulum'),
  ('Viburnum','trilobum','American cranberrybush', now(), 'Viburnum trilobum'),
  ('Washingtonia','filifera','California washingtonia', now(), 'Washingtonia filifera'),
  ('Ximenia','americana','tallowwood', now(), 'Ximenia americana'),
  ('Yucca','aloifolia','aloe yucca', now(), 'Yucca aloifolia'),
  ('Yucca','brevifolia','Joshua tree', now(), 'Yucca brevifolia'),
  ('Yucca','carnerosana','Carneros yucca', now(), 'Yucca carnerosana'),
  ('Yucca','elata','soaptree yucca', now(), 'Yucca elata'),
  ('Yucca','faxoniana','Faxon yucca', now(), 'Yucca faxoniana'),
  ('Yucca','gloriosa','moundlily yucca', now(), 'Yucca gloriosa'),
  ('Yucca','mohavensis','Mohave yucca', now(), 'Yucca mohavensis'),
  ('Yucca','rostrata','beaked yucca', now(), 'Yucca rostrata'),
  ('Yucca','schottii','Schotts yucca', now(), 'Yucca schottii'),
  ('Yucca','torreyi','Torrey yucca', now(), 'Yucca torreyi'),
  ('Yucca','treculeana','Trecul yucca', now(), 'Yucca treculeana'),
  ('Zanthoxylum','americanum','common prickly ash', now(), 'Zanthoxylum americanum'),
  ('Zanthoxylum','clava-herculis','Hercules club', now(), 'Zanthoxylum clava-herculis'),
  ('Zanthoxylum','coriaceum','Biscayne prickly ash', now(), 'Zanthoxylum coriaceum'),
  ('Zanthoxylum','fagara','lime prickly ash', now(), 'Zanthoxylum fagara'),
  ('Zanthoxylum','flavum','West Indies satinwood', now(), 'Zanthoxylum flavum'),
  ('Zanthoxylum','hirsutum','Texas Hercules club', now(), 'Zanthoxylum hirsutum');

INSERT INTO neodb.collection_methods (collection_method, collection_type_id, modified_on)
VALUES 
  ('beating ', 1, now()),
  ('sweeping', 1, now()),
  ('litter reducer', 1, now()),
  ('pooter/aspirator', 1, now()),
  ('net, aerial', 1, now()),
  ('sifting', 1, now()),
  ('funnel, extraction', 1, now()),
  ('net, aquatic', 1, now()),
  ('light, uv', 1, now()),
  ('light, mercury vapor', 1, now()),
  ('light, uv or mercury vapor', 1, now()),
  ('litter extractor', 1, now()),
  ('trap, lindgren funnel', 1, now()),
  ('trap, pitt-fall', 1, now()),
  ('extractor, Winkler', 1, now()),
  ('trap, pan', 1, now()),
  ('trap, flight intercept', 1, now()),
  ('trap, bait', 1, now()),
  ('rearing', 1, now()),
  ('trap, uv bucket', 1, now()),
  ('trap, bottle', 1, now()),
  ('trap, bucket', 1, now()),
  ('light, incandescent', 1, now()),
  ('in flight', 1, now()),
  ('hand collected ', 1, now()),
  ('funnel, Berlese', 1, now()),
  ('litter separator', 1, now()),
  ('trap, yellow pan', 1, now()),
  ('unknown', 1, now());


INSERT INTO neodb.notes(note, created_on, modified_on) VALUES ('unknown', now(), now());

--  HAVEN'T GOTTEN TO THESE ONES YET
--  fill associated_taxa

--  fill occurrences
--  fill opinions
--  fill occurrences_environments
--  fill occurrences_collectors
